package com.sati.model;
// Generated 14 ao�t 2023, 17:26:29 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FacturePharmacie generated by hbm2java
 */
@Entity
@Table(name = "facture_pharmacie", catalog = "hopitalarstm_bd")
public class FacturePharmacie implements java.io.Serializable {

	private Integer idFacturePharmacie;
	private Caisse caisse;
	private String codeFacturePharmacie;
	private Long montantFacturePharmacie;
	private Set<Caisse> caisses = new HashSet<Caisse>(0);
	private Set<LigneAchat> ligneAchats = new HashSet<LigneAchat>(0);

	public FacturePharmacie() {
	}

	public FacturePharmacie(Caisse caisse, String codeFacturePharmacie, Long montantFacturePharmacie,
			Set<Caisse> caisses, Set<LigneAchat> ligneAchats) {
		this.caisse = caisse;
		this.codeFacturePharmacie = codeFacturePharmacie;
		this.montantFacturePharmacie = montantFacturePharmacie;
		this.caisses = caisses;
		this.ligneAchats = ligneAchats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FACTURE_PHARMACIE", unique = true, nullable = false)
	public Integer getIdFacturePharmacie() {
		return this.idFacturePharmacie;
	}

	public void setIdFacturePharmacie(Integer idFacturePharmacie) {
		this.idFacturePharmacie = idFacturePharmacie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CAISSE")
	public Caisse getCaisse() {
		return this.caisse;
	}

	public void setCaisse(Caisse caisse) {
		this.caisse = caisse;
	}

	@Column(name = "CODE_FACTURE_PHARMACIE", length = 10)
	public String getCodeFacturePharmacie() {
		return this.codeFacturePharmacie;
	}

	public void setCodeFacturePharmacie(String codeFacturePharmacie) {
		this.codeFacturePharmacie = codeFacturePharmacie;
	}

	@Column(name = "MONTANT_FACTURE_PHARMACIE", precision = 12, scale = 0)
	public Long getMontantFacturePharmacie() {
		return this.montantFacturePharmacie;
	}

	public void setMontantFacturePharmacie(Long montantFacturePharmacie) {
		this.montantFacturePharmacie = montantFacturePharmacie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facturePharmacie")
	public Set<Caisse> getCaisses() {
		return this.caisses;
	}

	public void setCaisses(Set<Caisse> caisses) {
		this.caisses = caisses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facturePharmacie")
	public Set<LigneAchat> getLigneAchats() {
		return this.ligneAchats;
	}

	public void setLigneAchats(Set<LigneAchat> ligneAchats) {
		this.ligneAchats = ligneAchats;
	}

}
