package com.sati.model;
// Generated 14 ao�t 2023, 17:26:29 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "hopitalarstm_bd")
public class Filiere implements java.io.Serializable {

	private Integer idFiliere;
	private String codeFiliere;
	private String libelleFiliere;
	private Set<EtudiantArstm> etudiantArstms = new HashSet<EtudiantArstm>(0);

	public Filiere() {
	}

	public Filiere(String codeFiliere, String libelleFiliere, Set<EtudiantArstm> etudiantArstms) {
		this.codeFiliere = codeFiliere;
		this.libelleFiliere = libelleFiliere;
		this.etudiantArstms = etudiantArstms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FILIERE", unique = true, nullable = false)
	public Integer getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "CODE_FILIERE", length = 10)
	public String getCodeFiliere() {
		return this.codeFiliere;
	}

	public void setCodeFiliere(String codeFiliere) {
		this.codeFiliere = codeFiliere;
	}

	@Column(name = "LIBELLE_FILIERE", length = 50)
	public String getLibelleFiliere() {
		return this.libelleFiliere;
	}

	public void setLibelleFiliere(String libelleFiliere) {
		this.libelleFiliere = libelleFiliere;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<EtudiantArstm> getEtudiantArstms() {
		return this.etudiantArstms;
	}

	public void setEtudiantArstms(Set<EtudiantArstm> etudiantArstms) {
		this.etudiantArstms = etudiantArstms;
	}

}
