package com.sati.model;
// Generated 14 ao�t 2023, 17:26:29 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LigneAchat generated by hbm2java
 */
@Entity
@Table(name = "ligne_achat", catalog = "hopitalarstm_bd")
public class LigneAchat implements java.io.Serializable {

	private Integer idAchat;
	private FacturePharmacie facturePharmacie;
	private Medicament medicament;
	private Patient patient;
	private String codeAchat;
	private Integer quantiteMedicament;
	private Date dateAchat;

	public LigneAchat() {
	}

	public LigneAchat(Medicament medicament, Patient patient) {
		this.medicament = medicament;
		this.patient = patient;
	}

	public LigneAchat(FacturePharmacie facturePharmacie, Medicament medicament, Patient patient, String codeAchat,
			Integer quantiteMedicament, Date dateAchat) {
		this.facturePharmacie = facturePharmacie;
		this.medicament = medicament;
		this.patient = patient;
		this.codeAchat = codeAchat;
		this.quantiteMedicament = quantiteMedicament;
		this.dateAchat = dateAchat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ACHAT", unique = true, nullable = false)
	public Integer getIdAchat() {
		return this.idAchat;
	}

	public void setIdAchat(Integer idAchat) {
		this.idAchat = idAchat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_FACTURE_PHARMACIE")
	public FacturePharmacie getFacturePharmacie() {
		return this.facturePharmacie;
	}

	public void setFacturePharmacie(FacturePharmacie facturePharmacie) {
		this.facturePharmacie = facturePharmacie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MEDICAMENT", nullable = false)
	public Medicament getMedicament() {
		return this.medicament;
	}

	public void setMedicament(Medicament medicament) {
		this.medicament = medicament;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PATIENT", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "CODE_ACHAT", length = 10)
	public String getCodeAchat() {
		return this.codeAchat;
	}

	public void setCodeAchat(String codeAchat) {
		this.codeAchat = codeAchat;
	}

	@Column(name = "QUANTITE_MEDICAMENT")
	public Integer getQuantiteMedicament() {
		return this.quantiteMedicament;
	}

	public void setQuantiteMedicament(Integer quantiteMedicament) {
		this.quantiteMedicament = quantiteMedicament;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ACHAT", length = 19)
	public Date getDateAchat() {
		return this.dateAchat;
	}

	public void setDateAchat(Date dateAchat) {
		this.dateAchat = dateAchat;
	}

}
