package com.sati.model;
// Generated 4 juil. 2023, 21:54:33 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "hopitalarstm_bd")
public class Service implements java.io.Serializable {

	private Integer idService;
	private String codeService;
	private String libelleService;
	private Set<PersonnelArstm> personnelArstms = new HashSet<PersonnelArstm>(0);

	public Service() {
	}

	public Service(String codeService, String libelleService, Set<PersonnelArstm> personnelArstms) {
		this.codeService = codeService;
		this.libelleService = libelleService;
		this.personnelArstms = personnelArstms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SERVICE", unique = true, nullable = false)
	public Integer getIdService() {
		return this.idService;
	}

	public void setIdService(Integer idService) {
		this.idService = idService;
	}

	@Column(name = "CODE_SERVICE", length = 10)
	public String getCodeService() {
		return this.codeService;
	}

	public void setCodeService(String codeService) {
		this.codeService = codeService;
	}

	@Column(name = "LIBELLE_SERVICE", length = 50)
	public String getLibelleService() {
		return this.libelleService;
	}

	public void setLibelleService(String libelleService) {
		this.libelleService = libelleService;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<PersonnelArstm> getPersonnelArstms() {
		return this.personnelArstms;
	}

	public void setPersonnelArstms(Set<PersonnelArstm> personnelArstms) {
		this.personnelArstms = personnelArstms;
	}

}
