package com.sati.model;
// Generated 22 juil. 2023, 19:05:53 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeConsultation generated by hbm2java
 */
@Entity
@Table(name = "type_consultation", catalog = "hopitalarstm_bd")
public class TypeConsultation implements java.io.Serializable {

	private Integer idTypeConsultation;
	private String codeTypeConsultation;
	private Long montantTypeConsult;
	private Set<Consultation> consultations = new HashSet<Consultation>(0);

	public TypeConsultation() {
	}

	public TypeConsultation(String codeTypeConsultation, Long montantTypeConsult, Set<Consultation> consultations) {
		this.codeTypeConsultation = codeTypeConsultation;
		this.montantTypeConsult = montantTypeConsult;
		this.consultations = consultations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPE_CONSULTATION", unique = true, nullable = false)
	public Integer getIdTypeConsultation() {
		return this.idTypeConsultation;
	}

	public void setIdTypeConsultation(Integer idTypeConsultation) {
		this.idTypeConsultation = idTypeConsultation;
	}

	@Column(name = "CODE_TYPE_CONSULTATION", length = 10)
	public String getCodeTypeConsultation() {
		return this.codeTypeConsultation;
	}

	public void setCodeTypeConsultation(String codeTypeConsultation) {
		this.codeTypeConsultation = codeTypeConsultation;
	}

	@Column(name = "MONTANT_TYPE_CONSULT", precision = 12, scale = 0)
	public Long getMontantTypeConsult() {
		return this.montantTypeConsult;
	}

	public void setMontantTypeConsult(Long montantTypeConsult) {
		this.montantTypeConsult = montantTypeConsult;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeConsultation")
	public Set<Consultation> getConsultations() {
		return this.consultations;
	}

	public void setConsultations(Set<Consultation> consultations) {
		this.consultations = consultations;
	}

}
